baseURL: "https://kingtuo123.com/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: King's Blog
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: false
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 1
                - name: Categories
                  url: categories/
                  weight: 2
                - name: Tags
                  url: tags/
                  weight: 3
                - name: Search
                  url: search/
                  weight: 4



outputs:
    home:
        - HTML
        - JSON

params:
    env: production
    description: "kingtuo123's blog"
    author: ""
    label:
      text: "Notes"
    defaultTheme: light
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    homeInfoParams:
        Title: ":  )"
        Content: "清风徐来，水波不兴"
    assets:
      disableHLJS: true




markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
      anchorLineNos: true
      codeFences: true
      guessSyntax: true
      lineNos: false
      noClasses: false
      style: nord


