name: github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitmodules'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Blog
        run: hugo --minify

      - name: Zip Blog
        uses: vimtor/action-zip@v1.1
        with:
          files: ./public
          dest: Blog.zip

      - name: Setup OSS
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-accelerate.aliyuncs.com"
          access-key-id: ${{ secrets.ID }}
          access-key-secret: ${{ secrets.SECRET }}

      - name: Empty OSS
        run: ossutil rm -rf oss://kingtuo123 --include "*"

      - name: Upload Blog.zip
        run: ossutil cp -f Blog.zip oss://kingtuo123/

      - name: Wait For Unzipping
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 60s

      - name: Remove Blog.zip From OSS
        run: ossutil rm -f oss://kingtuo123/Blog.zip
